### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by julianpoemp** [echo66/OLA-TS.js#6]
I found this project while searching for a solution of time-stretching audio via javascript. Because this project is quite old and I didn't find any email address, I like to ask some questions here:

1. Do you need contributors? I could help you for this project and do the following: Restructure the code, create an npm package, definitions for typescript, improve documentation and examples.

2. How can we change buffered-ts.js in order to allow audiobuffers with only one channel?

3. The repository offers buffered-ts.js, but the demo page uses buffered-ola.js. Which one is newer?

**Comment by combs** [comment]
@julianpoemp if you are still interested in contributing to OLA-TS, I forked the repo, rearranged, and published to npm as `ola-ts`. Would welcome any other contributions at https://github.com/combs/OLA-TS.js
